name: Test, Lint, Type Check
on:
  workflow_call:
    inputs:
      parent:
        required: true
        type: string
      build:
        required: true
        type: boolean


# Given a set of parents
jobs:
# List the directories under the parents
  find-subdirs:
    name: Find Subdirectories
    uses: ./.github/workflows/list-dirs.yaml
    with: 
      parent: ${{ inputs.parent }}
  # test, lint, and type check every package/app under parent
  lint:
    name: "Python: Lint"
    needs: [find-subdirs]
    strategy:
      matrix:
        subdir: ${{needs.find-subdirs.outputs.folders}}
    uses: ./.github/workflows/python-linting.yaml
    with:
      directory: ${{inputs.parent}}/${{ matrix.subdir }}
  test:
    name: "Python: Test"
    needs: [find-subdirs]
    strategy:
      matrix:
        subdir: ${{ fromJson(needs.find-subdirs.outputs.folders) }}
    uses: ./.github/workflows/python-unit-test.yaml
    with:
      directory: ${{inputs.parent}}/${{ matrix.subdir }}
  type:
    name: "Python: Type Check"
    needs: [find-subdirs]
    strategy:
      matrix:
        subdir: ${{ fromJson(needs.find-subdirs.outputs.folders) }}
    uses: ./.github/workflows/python-type-check.yaml
    with:
      directory: ${{inputs.parent}}/${{ matrix.subdir }}
  build:
    if: ${{ inputs.build }} == true
    needs: [find-subdirs, test, lint, type]
    strategy:
      matrix:
        subdir: ${{ fromJson(needs.find-subdirs.outputs.folders) }}
    uses: ./.github/workflows/docker-push.yaml
    with:
      directory: ${{inputs.parent}}/${{ matrix.subdir }}

