name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      build:
        default: true
        type: boolean
  
jobs:
  test-lint-check-build:
    strategy:
      matrix:
        parent:
          - apps
    uses: ./.github/workflows/build-test-subdirs.yaml
    with:
      parent: ${{ matrix.parent }}
      build: ${{ inputs.build }}
    
