on:
  pull_request:
    types:
      - closed
    branches:
      ["main"]
  
jobs:
    build-test:
      uses: ./.github/workflows/python-app.yaml
    # docker-build:
    #   uses: ./.github/workflows/docker-image.yaml
    docker-build-and-push:
      with:
        repository: test-repo
      needs: build-test
      uses: ./.github/workflows/docker-push.yaml
