on:
  pull_request:
    types:
      - closed
    branches:
      ["main"]
  
jobs:
    subdirs:
      - name: Test, Lint, and Type Check Pacakges
        with: 
          parent: "apps"
        
    unit-test:
      uses: ./.github/workflows/python-unit-test.yaml
    linting:
      uses: ./.github/workflows/python-linting.yaml
    type-checking:
      uses: ./.github/workflows/python-type-check.yaml
    # docker-build:
    #   uses: ./.github/workflows/docker-image.yaml
    docker-build-and-push:
      with:
        repository: test-repo
      needs: [build-test,linting,type-checking]
      uses: ./.github/workflows/docker-push.yaml
