name: "Python: Pytest"

on:
  pull_request:
    branches: ["main"]
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash 
    - name: Rye Sync
      run: |
        # Install package with rye sync
        source "$HOME/.rye/env"
        rye sync
   
    - name: Test with pytest
      run: |
        source "$HOME/.rye/env"
        rye run pytest -vv tests
    