name: "Python: Lint and Test"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint with ruff
      run: |
        # Lint with ruff
        source "$HOME/.rye/env"
        rye run ruff check .
    - name: Test with pytest
      run: |
        source "$HOME/.rye/env"
        rye run pytest -vv tests
    - name: MyPy Check
      run: |
        source "$HOME/.rye/env"
        rye run mypy