name: "Python: Lint and Test"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  steps:
    - name: Set up Rye
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash 
    - name: Rye Sync
      run: |
        # Install package with rye sync
        source "$HOME/.rye/env"
        rye sync